dist: trusty
language: node_js
node_js:
 - "13.1.0"

# addons:
#  apt:
#   sources:
#    - google-chrome
#   package:
#    - google-chrome-stable

cache:
 directories:
  - ./node_modules

script:
 - ng test --watch=false --browsers=ChromeHeadless

install:
 - npm install
 - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN